### PR TITLE
Fix ZMQ_HEARTBEAT_TTL maximum value check

### LINKED ISSUE #3136: Cannot set ZMQ_HEARTBEAT_TTL to more than 655.3 seconds
# Issue description

The maximum value for ZMQ_HEARTBEAT_TTL is not correctly checked.

# Environment

* libzmq version (commit hash if unreleased): 50374bf
* OS: any

# Minimal test code / Steps to reproduce the issue

```
int value = 655400;
zmq_setsockopt (socket, ZMQ_HEARTBEAT_TTL, &value, sizeof (value))
```

# What's the actual result? (include assertion message & call stack if applicable)

-1 / EINVAL

# What's the expected result?

0

### PR DESCRIPTION
**Pull request by sigiesec**
Fixes https://sonarcloud.io/project/issues?id=zeromq-libzmq&issues=AWOS_NBc_Tl7jhO8m4MM&open=AWOS_NBc_Tl7jhO8m4MM en passant

Fixes #3136

### CODE REVIEW

File: src/options.cpp [hunk 1]
```diff
@@ -665,8 +667,8 @@ int zmq::options_t::setsockopt (int option_,
 
         case ZMQ_HEARTBEAT_TTL:
             // Convert this to deciseconds from milliseconds
-            value = value / 100;
-            if (is_int && value >= 0 && value <= 6553) {
```
Comment (bluca) [inline src/options.cpp]: I'm not sure this was a typo? Right now the max TTL is one hour and a half, this would make it 18 hours which is a bit much

https://rfc.zeromq.org/spec:37/ZMTP

Comment (sigiesec) [reply src/options.cpp]: Ok... that's really in the spec... But it is a very strange value, isn't it? ;)

Anyway, I will change it back to the previous value, but it makes sense to add the tests, so I keep the PR open and fix.

Comment (bluca) [reply src/options.cpp]: It's very very strange :-)

The spec is in DRAFT form, so feel free to amend it to something less strange if you want to

Comment (sigiesec) [reply src/options.cpp]: Oh, I checked it again... and now I understand, but it is even a bit weirder:

First, the spec says:
> The ping-ttl is a 16-bit unsigned integer in network order that MAY be zero or MAY contain a time-to-live *measured in tenths of seconds*

This would allow values up to UINT16_MAX==65535 deciseconds, as my PR implements.

Then it says:
> The maximum TTL is 6553 seconds

This would allow values up to 65530 deciseconds

So UINT16_MAX is almost correct according to the spec, in fact it were UINT16_MAX - UINT16_MAX % 10.

However, I think this second sentence is not meant to restrict the value, but simply explain the consequence of having a 16 bit unsigned integer specifying deciseconds.

Maybe the wording in the spec should be changed to:
> As a consequence, the maximum TTL is 6553.5 seconds

Comment (bluca) [reply src/options.cpp]: right, that makes even more sense, feel free to send a pr to the rfc and I'll merge that too

Comment (sigiesec) [reply src/options.cpp]: Ok, I will also add this to doc/zmq_setsockopt.txt

Comment (sigiesec) [reply src/options.cpp]: Done

File: tests/test_heartbeats.cpp [hunk 2]
```diff
@@ -366,6 +374,49 @@ DEFINE_TESTS (pull, push, ZMQ_PULL, ZMQ_PUSH)
 DEFINE_TESTS (sub, pub, ZMQ_SUB, ZMQ_PUB)
 DEFINE_TESTS (pair, pair, ZMQ_PAIR, ZMQ_PAIR)
 
+const int deciseconds_per_millisecond = 100;
+// TODO the maximum value is not documented, should it?
```
Comment (bluca) [inline tests/test_heartbeats.cpp]: the TODO can go now?

Comment (sigiesec) [reply tests/test_heartbeats.cpp]: Right, removed it
