### PR TITLE
Problem: assertion in src\select.cpp:111 on Windows or hang on zmq_ctx_destroy

### LINKED ISSUE #2723: Assertion failed: Invalid argument (src\select.cpp:111) resp. hang in zmq_ctx_destroy
# Issue description

I get an assertion failure during context shutdown.

# Environment

* libzmq version (commit hash if unreleased): unreleased, 7783d027c96f2fd7f5ea483c75790db11ad4265e
* OS: Windows 7 64-Bit

# Minimal test code / Steps to reproduce the issue

1. Change count in test_get_peer_state to a larger number, e.g. 100000
2. Run test_router_mandatory

# What's the actual result? (include assertion message & call stack if applicable)

Assertion failed: Invalid argument (src\select.cpp:111) with the following stacktrace:

```
 	KernelBase.dll!RaiseException()	Unknown
>	libzmq-v140-mt-gd-4_2_3.dll!zmq::zmq_abort(const char * errmsg_) Line 89	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::select_t::rm_fd(unsigned __int64 handle_) Line 111	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::io_object_t::rm_fd(unsigned __int64 handle_) Line 72	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::stream_engine_t::unplug() Line 277	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::stream_engine_t::error(zmq::stream_engine_t::error_reason_t reason) Line 998	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::stream_engine_t::in_event() Line 327	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::select_t::loop() Line 315	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::select_t::worker_routine(void * arg_) Line 390	C++
 	libzmq-v140-mt-gd-4_2_3.dll!thread_routine(void * arg_) Line 47	C++
 	ucrtbased.dll!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92	C++
 	ucrtbased.dll!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

reason is connection_error here

The main thread is here:
```
>	libzmq-v140-mt-gd-4_2_3.dll!zmq::signaler_t::wait(int timeout_) Line 268	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::mailbox_t::recv(zmq::command_t * cmd_, int timeout_) Line 81	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq::ctx_t::terminate() Line 179	C++
 	libzmq-v140-mt-gd-4_2_3.dll!zmq_ctx_term(void * ctx_) Line 175	C++
 	test_router_mandatory.exe!test_get_peer_state() Line 144	C++
 	test_router_mandatory.exe!main() Line 220	C++
```

# What's the expected result?

Successful completion of zmq_ctx_destroy

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: Fix zmq::select_t::rm_fd and zmq::session_base_t::engine_error

Fixes #2723

### CODE REVIEW

File: src/select.cpp [hunk 1]
```diff
@@ -99,22 +99,19 @@ zmq::select_t::find_fd_entry_by_handle (fd_entries_t &fd_entries,
          ++fd_entry_it)
         if (fd_entry_it->fd == handle_)
             break;
-    zmq_assert (fd_entry_it != fd_entries.end ());
 
     return fd_entry_it;
 }
 
-void zmq::select_t::rm_fd (handle_t handle_)
+bool zmq::select_t::try_remove_fd_entry (
```
Comment (bluca) [inline src/select.cpp]: This will trigger static analysers and picky compiler since it's not used elsewhere, so it's probably a good idea to wrap it in \#ifdef windows

File: src/session_base.cpp [hunk 2]
```diff
@@ -434,13 +434,19 @@ void zmq::session_base_t::engine_error (
...
         case stream_engine_t::timeout_error:
         case stream_engine_t::connection_error:
-            if (active)
+            if (active) {
                 reconnect ();
-            else
-                terminate ();
-            break;
+                break;
+            }
```
Comment (bluca) [inline src/session_base.cpp]: this will trigger compiler warnings, so you'll want to add ```/* fallthrough */``` just before the next case

Comment (bluca) [reply src/session_base.cpp]: actually the case above is already like that, so never mind

Comment (sigiesec) [reply src/session_base.cpp]: I saw you changed that already, thanks :)
