### PR TITLE
Problem:  global random init/deinit breaks existing applications

### LINKED ISSUE #2991: New invalid argument error in libzmq, mutex.hpp:142
# Issue description
One of the unit test suites we have finishes all of the test cases (which involve starting up and shutting down zmq, probably at least 50 times), but then there is an invalid argument error by zmq after boost reports the number of test cases that have passed. The first time observing this issue was on March 9th, but we cache builds of dependencies. The cached version on our develop branch was last updated February 27. Switching our builds to use the last tagged release (v4.2.3) makes the error go away.

The output for the zmq error: Invalid argument (/home/travis/build/GMLC-TDC/HELICS-src/libzmq/src/mutex.hpp:142)

# Environment
Travis CI Linux VMs using gcc-6, gcc-4.9, and clang-3.6

* libzmq version (commit hash if unreleased): One of the commits between February 27 and March 9.
* OS: Linux

# Minimal test code / Steps to reproduce the issue

1.  Checkout and build GMLC-TDC/HELICS-src develop branch
2. Run key-tests test suite. I haven't narrowed it down to a specific zeromq commit, or line in our test suite. If that changes I'll provide an update here.

# What's the actual result? (include assertion message & call stack if applicable)
https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/353188544 - see error at the bottom

# What's the expected result?
https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/353393510

### PR DESCRIPTION
**Pull request by bluca**
Solution: restrict it only to the original issue #2632, Tweetnacl on
*NIX when using /dev/urandom, ie: without the new Linux getrandom()
syscall.

Existing applications might use atexit to register cleanup functions
(like CZMQ does), and the current change as-is imposes an ordering
that did not exist before - the context MUST be created BEFORE
registering the cleanup with atexit. This is a backward incompatible
change that is reported to cause aborts in some applications.

Although libsodium's documentation says that its initialisation APIs
is not thread-safe, nobody has ever reported an issue with it, so
avoiding the global init/deinit in the libsodium case is the less
risky option we have.

Tweetnacl users on Windows and on Linux with getrandom (glibc 2.25 and
Linux kernel 3.17) are not affected by the original issue.

Fixes #2991

### CODE REVIEW

File: src/random.cpp [hunk 1]
```diff
@@ -86,6 +86,13 @@ uint32_t zmq::generate_random ()
 //  order fiasco, this is done using function-local statics, if the
 //  compiler implementation supports thread-safe initialization of those.
 //  Otherwise, we fall back to global statics.
+//  HOWEVER, this initialisation code adds a race condition when an
```
Comment (sigiesec) [inline src/random.cpp]: It is not a race condition (this has nothing to do with concurrency). Maybe:

```
HOWEVER, this initialisation code imposes ordering constraints, which are not obvious to users of libzmq, and may lead to problems if atexit or similar methods are used for cleanup.
```

File: src/random.cpp [hunk 2]
```diff
@@ -140,6 +145,14 @@ static void manage_random (bool init)
             randombytes_close ();
         }
     }
+
+#elif defined(ZMQ_USE_LIBSODIUM)
+    if (init) {
+        int rc = sodium_init ();
```
Comment (sigiesec) [inline src/random.cpp]: Since this does not use the refcount, this means that sodium_init and randombytes_close will be called for each context. Is that what you meant?

Comment (bluca) [reply src/random.cpp]: Yes - that is how it worked before my initial change. They were called inline in the Context class constructor and destructor.

In reality I think randombytes_close is mostly a no-op in libsodium, and nobody ever reported a problem with the multiple sodium_init calls either (with libsodium again).

File: src/random.cpp (hunk 1 above)
Comment (bluca) [reply src/random.cpp]: Thanks, updated

File: src/random.cpp (hunk 2 above)
Comment (sigiesec) [reply src/random.cpp]: Ok, just wanted to be sure.

Comment (minrk) [reply src/random.cpp:152]: Adding a clarifying correction for anyone who comes here in the future: this is only a no-op if getrandom is unavailable (already excluded in the above condition). If not, libsodium has all the same threadsafety issues as tweetnacl, so this PR causes crashes because libsodium has all the same requirements as tweetnacl here.
