### PR TITLE
Problem: assertion failure in poller_base.cpp:42

### LINKED ISSUE #2925: Assertion failure in poller_base.cpp:42
# Issue description

An assertion is triggered:
```
Assertion failed: get_load () == 0 (C:\projects\libzmq\src\poller_base.cpp:42)
```

See, e.g. here: https://ci.appveyor.com/project/sigiesec/libzmq/build/build-329/job/2jkd94g6rxnh6h1a#L1026

# Environment

* libzmq version (commit hash if unreleased): 70521390420216a0bd2674cb34c2835e5d525a6f, 78dd28460132b37797fd6e8fff4d2bc2ccde2ae4
* OS: Windows 7 64-bit
* Using select_t poller

# Minimal test code / Steps to reproduce the issue

1. Run test_router_mandatory repeatedly.

# What's the actual result? (include assertion message & call stack if applicable)

```
Assertion failed: get_load () == 0 (C:\projects\libzmq\src\poller_base.cpp:42)
```

# What's the expected result?

No assertion.

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: wait until all fds have been unregistered before exiting select_t::loop

Fixes #2925 

This PR requires #2908 to be merged first.

### CODE REVIEW

**Comment by bluca** [comment]
It looks like there are still extra commits here? Rebase gone wrong?

**Comment by sigiesec** [comment]
There was one extra commit I had cherry-picked from another PR. I now rebased again.

**Comment by sigiesec** [comment]
Integrated #2918 here, changes should now be here uniquely.

**Comment by bluca** [comment]
Ok - I'll let the CI run on this given there's a few new changes

**Comment by sigiesec** [comment]
Looks good now IMO. Unfortunately, there appears to be some instability with clang-format when comments precede a preprocessor directive. I will check separately if this can be fixed by tweaking the clang-format configuration.

File: tests/test_timers.cpp [hunk 1]
```diff
@@ -154,21 +154,34 @@ int main (void)
...
     assert (timer_id);
 
-    //  Timer should be invoked yet
+    //  Timer should not have been invoked yet
     int rc = zmq_timers_execute (timers);
     assert (rc == 0);
-    assert (!timer_invoked);
+
+#ifdef ZMQ_BUILD_DRAFT_API
+    if (zmq_stopwatch_intermediate (stopwatch) < full_timeout) {
```
Comment (bluca) [inline tests/test_timers.cpp]: @sigiesec with older versions of gcc there's this error:

```
[  220s] cc1plus: warnings being treated as errors
[  220s] tests/test_timers.cpp: In function 'int main()':
[  220s] tests/test_timers.cpp:169: error: comparison between signed and unsigned integer expressions
[  220s] tests/test_timers.cpp:181: error: comparison between signed and unsigned integer expressions
```

Do you know what the issue is? Otherwise I'll try to find time over the weekend
